version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
    - ${NGINX_HOST_HTTP_PORT}:80
    links:
      - app
    volumes:
      - ./:${APP_CODE_PATH_CONTAINER}
  app:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    volumes:
      - ./:${APP_CODE_PATH_CONTAINER}
      - ./docker/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
